# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SinaApiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, null=True, verbose_name='sina code')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='access token')),
            ],
        ),
    ]
