# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sina', '0003_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=10000, verbose_name='\u6b63\u6587\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='article',
            name='send_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='\u53d1\u9001\u65f6\u95f4'),
        ),
    ]
