# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-05 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sina', '0008_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='\u5927\u7c7b\u6807\u9898')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
