# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-05 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sina', '0009_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationPointCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='\u8003\u70b9\u7c7b\u522b\u540d\u79f0')),
                ('level', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=64, verbose_name='\u8003\u70b9\u7ea7\u522b')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_send', models.BooleanField(default=False, verbose_name='\u662f\u5426\u53d1\u5e03')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=64, verbose_name='\u8003\u8bd5\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='examinationpointcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sina.Category', verbose_name='\u8003\u8bd5\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='examinationpointcategory',
            name='examination_point',
            field=models.ManyToManyField(related_name='_examinationpointcategory_examination_point_+', to='sina.ExaminationPointCategory', verbose_name='\u8003\u70b9\u7c7b\u522b'),
        ),
    ]
