# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-05 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sina', '0011_auto_20180405_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='\u95ee\u9898\u6807\u9898')),
                ('answer', models.CharField(max_length=16, verbose_name='\u95ee\u9898\u7b54\u6848')),
                ('answer_description', models.CharField(max_length=1028, verbose_name='\u7b54\u6848\u63cf\u8ff0')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_send', models.BooleanField(default=False, verbose_name='\u662f\u5426\u53d1\u5e03')),
                ('look_num', models.BigIntegerField(verbose_name='\u6d4f\u89c8\u6b21\u6570')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sina.Category', verbose_name='\u8003\u8bd5\u7c7b\u522b')),
                ('examination_point', models.ManyToManyField(blank=True, null=True, to='sina.ExaminationPointCategory', verbose_name='\u8003\u70b9\u7c7b\u522b')),
            ],
        ),
    ]
