# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-06 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sina', '0012_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_num', models.CharField(max_length=512, verbose_name='\u95ee\u9898\u9009\u9879\u5e8f\u53f7')),
                ('item_des', models.CharField(max_length=512, verbose_name='\u95ee\u9898\u9009\u9879\u63cf\u8ff0')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sina.Questions')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='questionitems',
            unique_together=set([('question', 'item_num')]),
        ),
    ]
