# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-07 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sina', '0013_auto_20180406_0417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['look_num', '-created_datetime']},
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_send',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u53d1\u5e03'),
        ),
        migrations.AlterField(
            model_name='examinationpointcategory',
            name='is_send',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u53d1\u5e03'),
        ),
        migrations.AlterField(
            model_name='questionitems',
            name='item_des',
            field=models.TextField(max_length=512, verbose_name='\u95ee\u9898\u9009\u9879\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='questionitems',
            name='item_num',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=512, verbose_name='\u95ee\u9898\u9009\u9879\u5e8f\u53f7'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='is_send',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u53d1\u5e03'),
        ),
    ]
