# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-30 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sina', '0014_auto_20180407_0541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionitems',
            options={'ordering': ['item_num']},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['-look_num', '-created_datetime']},
        ),
        migrations.AlterField(
            model_name='questionitems',
            name='item_num',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K')], max_length=512, verbose_name='\u95ee\u9898\u9009\u9879\u5e8f\u53f7'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='is_send',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u53d1\u5e03'),
        ),
    ]
