# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sina', '0002_sinaapidata_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('content', models.CharField(max_length=10000, verbose_name='\u6b63\u6587\u5185\u5bb9')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=b'/media/', verbose_name='\u56fe\u7247\u5730\u5740')),
                ('summary', models.CharField(max_length=64, verbose_name='\u6587\u7ae0\u5bfc\u8bed')),
                ('text', models.CharField(max_length=1900, verbose_name='\u4e0e\u5176\u7ed1\u5b9a\u77ed\u5fae\u535a\u5185\u5bb9')),
                ('send_datetime', models.DateTimeField(auto_now=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_send', models.BooleanField(default=False, verbose_name='\u662f\u5426\u53d1\u5e03')),
            ],
        ),
    ]
